# Generated by Django 5.0.2 on 2024-07-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_student_alter_admin_password_alter_admin_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='FatherName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Place',
        ),
    ]
