# Generated by Django 5.0.2 on 2024-07-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_attendence_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='Attendence',
        ),
    ]
