# Generated by Django 5.0.2 on 2024-07-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_teacher_teacherid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=30)),
                ('SubCode', models.CharField(max_length=10)),
            ],
        ),
    ]
