# Generated by Django 5.0.2 on 2024-07-29 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0023_remove_feedetailsforclass_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedetailsforclass',
            name='Class',
        ),
        migrations.AddField(
            model_name='feedetailsforclass',
            name='Class',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Admin.class'),
            preserve_default=False,
        ),
    ]
