# Generated by Django 5.0.2 on 2024-08-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0029_attendencedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendencedetails',
            name='Date',
            field=models.DateField(default='2023-08-01'),
        ),
    ]
