# Generated by Django 5.0.2 on 2024-08-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0034_alter_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Subject',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
