# Generated by Django 5.0.2 on 2024-08-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0037_exammarks_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammarks',
            name='Marks',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
