# Generated by Django 5.0.2 on 2024-08-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0038_alter_exammarks_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammarks',
            name='Marks',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
