# Generated by Django 5.0.2 on 2024-07-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_remove_teacher_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='MobileNo',
            field=models.CharField(default='0000', max_length=10),
            preserve_default=False,
        ),
    ]
