# Generated by Django 5.0.2 on 2024-07-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_teacher_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.CharField(max_length=10)),
                ('Month', models.CharField(max_length=10)),
            ],
        ),
    ]
