# Generated by Django 5.0.2 on 2024-07-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_attendence_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='ClassTeacher',
            field=models.CharField(default='Class1', max_length=10),
            preserve_default=False,
        ),
    ]
