# Generated by Django 5.0.2 on 2024-07-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0025_alter_feedetailsforclass_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeeDetailsForClass',
            new_name='UpdateFee',
        ),
    ]
