# Generated by Django 5.0.2 on 2024-08-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_remove_attendence_date_attendence_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendenceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('Attendence', models.CharField(max_length=5)),
            ],
        ),
    ]
