# Generated by Django 5.0.2 on 2024-08-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0032_attendencedetails_attendencedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Profile',
            field=models.ImageField(null=True, upload_to='Profile/'),
        ),
    ]
