# Generated by Django 5.0.2 on 2024-08-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0033_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.CharField(max_length=6),
        ),
    ]
