# Generated by Django 5.0.2 on 2024-08-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0041_examtype_maxmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Profile',
            field=models.ImageField(null=True, upload_to='Profile/'),
        ),
    ]
