# Generated by Django 5.0.2 on 2024-08-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0042_teacher_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherID', models.CharField(max_length=20)),
                ('Timetable', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
