# Generated by Django 5.0.2 on 2024-07-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_posters'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='MobileNo',
            field=models.CharField(default='000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.CharField(default='000', max_length=15),
            preserve_default=False,
        ),
    ]
