# Generated by Django 5.0.2 on 2024-07-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Image',
            field=models.ImageField(default='Class1', upload_to='TimeTable/'),
            preserve_default=False,
        ),
    ]
