# Generated by Django 5.0.2 on 2024-07-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0022_feedetailsforclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedetailsforclass',
            name='Class',
        ),
        migrations.AddField(
            model_name='feedetailsforclass',
            name='Class',
            field=models.ManyToManyField(to='Admin.class'),
        ),
    ]
