# Generated by Django 5.0.2 on 2024-08-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0030_alter_attendencedetails_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendencedetails',
            name='Date',
        ),
    ]
