# Generated by Django 5.0.2 on 2024-07-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_student_mobileno_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Password',
            field=models.CharField(default='000', max_length=15),
            preserve_default=False,
        ),
    ]
