# Generated by Django 5.0.2 on 2024-07-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
