# Generated by Django 5.0.2 on 2024-07-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_timetable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Class',
            field=models.CharField(default='Class1', max_length=5),
            preserve_default=False,
        ),
    ]
