# Generated by Django 5.0.2 on 2024-07-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='TimeTable/'),
        ),
    ]
