# Generated by Django 5.0.2 on 2024-07-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='Attendence',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
