# Generated by Django 5.0.2 on 2024-08-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0026_rename_feedetailsforclass_updatefee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='Month',
        ),
        migrations.AddField(
            model_name='attendence',
            name='Date',
            field=models.DateField(default='2023-08-01'),
        )
    ]
