# Generated by Django 5.0.2 on 2024-08-01 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0031_remove_attendencedetails_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendencedetails',
            name='AttendenceDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
