# Generated by Django 5.0.2 on 2024-08-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0035_teacher_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentRollNo', models.CharField(max_length=15)),
                ('StudentName', models.CharField(max_length=30)),
                ('Subject', models.CharField(max_length=20)),
                ('ExamType', models.CharField(max_length=20)),
                ('Marks', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExamType', models.CharField(max_length=20)),
                ('Access', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.CharField(max_length=7),
        ),
    ]
