# Generated by Django 5.0.2 on 2024-08-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0036_exammarks_examtype_alter_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammarks',
            name='Class',
            field=models.CharField(default='Class-1', max_length=10),
            preserve_default=False,
        ),
    ]
