# Generated by Django 5.0.2 on 2024-07-25 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_class'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedetails',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_details', to='Admin.student'),
        ),
    ]
