# Generated by Django 5.0.2 on 2024-07-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_alter_feedetails_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedetails',
            old_name='DueAmount',
            new_name='Due',
        ),
        migrations.RenameField(
            model_name='feedetails',
            old_name='TotalPaidAmount',
            new_name='LatestPaidFee',
        ),
        migrations.RemoveField(
            model_name='feedetails',
            name='NowPaidAmount',
        ),
        migrations.RemoveField(
            model_name='feedetails',
            name='student',
        ),
        migrations.AddField(
            model_name='feedetails',
            name='Class',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedetails',
            name='StudentName',
            field=models.CharField(default='0', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedetails',
            name='StudentRollNo',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedetails',
            name='TotalPaidFee',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
            preserve_default=False,
        ),
    ]
