# Generated by Django 5.0.2 on 2024-07-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_alter_feedetails_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetails',
            name='Discount1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
