# Generated by Django 5.0.2 on 2024-08-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_transactionhistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedetails',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='Date',
            field=models.DateField(),
        ),
    ]
