# Generated by Django 5.0.2 on 2024-09-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_remove_feedetails_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RollNo', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('MailId', models.EmailField(max_length=30)),
                ('DOB', models.DateField()),
                ('Nationality', models.CharField(max_length=10)),
                ('Religion', models.CharField(max_length=10)),
                ('FatherName', models.CharField(max_length=30)),
                ('FatherOccupation', models.CharField(max_length=50)),
                ('FatherMobileNo', models.IntegerField()),
                ('FatherMailId', models.EmailField(max_length=254)),
                ('MatherName', models.CharField(max_length=30)),
                ('MatherOccupation', models.CharField(max_length=50, null=True)),
                ('MatherMobileNo', models.IntegerField(null=True)),
                ('MatherMailId', models.EmailField(max_length=254, null=True)),
                ('PermanentAddress', models.CharField(max_length=50)),
                ('CurrentAddress', models.CharField(max_length=50)),
            ],
        ),
    ]
