# Generated by Django 5.0.2 on 2024-09-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0015_studentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='FullName',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
