# Generated by Django 5.0.2 on 2024-09-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0016_studentdetails_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetails',
            old_name='MatherMailId',
            new_name='MotherMailId',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='MatherMobileNo',
            new_name='MotherMobileNo',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='MatherName',
            new_name='MotherName',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='MatherOccupation',
            new_name='MotherOccupation',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='Religion',
        ),
    ]
