# Generated by Django 5.0.2 on 2024-09-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0017_rename_mathermailid_studentdetails_mothermailid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='StudentMobileNo',
            field=models.CharField(default='0', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='FatherMobileNo',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='MotherMobileNo',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
