# Generated by Django 5.0.2 on 2024-07-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_remove_feedetails_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetails',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='TransactionNo',
            field=models.CharField(max_length=30),
        ),
    ]
