# Generated by Django 5.0.2 on 2024-07-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_feedetails_date_alter_feedetails_transactionno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedetails',
            name='Discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
