# Generated by Django 5.0.2 on 2024-07-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_rename_dueamount_feedetails_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetails',
            name='Date',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedetails',
            name='Discount',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedetails',
            name='TransactionNo',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
