# Generated by Django 5.0.2 on 2024-07-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_feedetails_date_feedetails_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedetails',
            name='Date',
        ),
    ]
