# Generated by Django 5.0.2 on 2024-07-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_remove_feedetails_date_remove_feedetails_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentRollNo', models.CharField(max_length=10)),
                ('StudentName', models.CharField(max_length=30)),
                ('Class', models.CharField(max_length=10)),
                ('TotalFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Discount1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalPaidFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LatestPaidFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TransactionNo', models.CharField(max_length=30)),
            ],
        ),
    ]
