# Generated by Django 5.0.2 on 2024-08-08 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_feedetails_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
