# Generated by Django 5.0.2 on 2024-08-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_alter_feedetails_date_alter_transactionhistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedetails',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='feedetails',
            name='TransactionNo',
        ),
    ]
